<hr style="border:5px solid #108999"> </hr>

# Python Variables and Types of Data <hr style="border:4.5px solid #108999"> </hr>

## Variables

Create a variable with name "x" and a value of 10. Execute.

In [1]:
x = 10

Tell the computer to show you the value of that variable.

In [2]:
print(x)

10


Can you think of a second way to obtain the same result? 

In [3]:
x

10

On the same line, create four new variables: a,b,c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [4]:
a,b,c,d = (10, 20, 30, 40)

Tell the computer to show you the value corresponding to the variable "b".

In [5]:
b

20

Do the same for "d".

In [6]:
d

40

## Numbers and Boolean Values

Create a variable equal to "True".

In [7]:
a = True

Check its type.

In [8]:
type(a)

bool

Create a variable equal to 99.

In [9]:
b = 99

Check its type.

In [10]:
type(b)

int

Check the type of the value 0.99. 

In [11]:
type(0.99)

float

Turn 99 into a *float*.

In [12]:
float(99)

99.0

Turn 0.99 into an integer. What value did you get?

In [13]:
int(0.99)

0

## Strings

Assign the value of 100 to the variable "m".

In [14]:
m = 100

With the help of the variable "m", write one line of code where the output after executuion would be *100 days*.

*Hint:* *You could provide four answers to this question!*

In [18]:
print(str(100) + " days")

100 days


In [16]:
print(f'{m} days')

100 days


In [29]:
print(str(100) , "days")

100 days


Produce an output equal to *It's cool, isn't it?*

In [19]:
print("It's cool, isn't it")

It's cool, isn't it


In [194]:
print('It\'s cool, isn\'t it?')

It's cool, isn't it?


Fix the string below.

In [21]:
print("Don't be shy")

Don't be shy


Produce an output equal to *Click "OK"*.

In [195]:
print('Click "OK"')

Click "OK"


Include a plus sign in your line of code to produce *'Big Houses'*.

In [26]:
print("Big" + " Houses")

Big Houses


Include a trailing comma in your line of code to produce *Big Houses*.

In [27]:
print("Big", " Houses")

Big  Houses


<hr style="border:5px solid #108999"> </hr>

# Basic Python Syntax <hr style="border:4.5px solid #108999"> </hr>

## Arithmetic operators

Combine 15 and 23.

In [30]:
15 + 23

38

Subtract 50 from 26.

In [196]:
26 - 50

-24

Divide 20 by 4.

In [32]:
20 / 4

5.0

Divide 22 by 4.

In [33]:
22 / 4 

5.5

Obtain the remainder of the division of 22 by 4.

In [34]:
22 % 4

2

Divide the float 22 by 4.

In [35]:
22.0 / 4

5.5

Multiply 6 by 8.

In [36]:
6 * 8

48

Raise 15 to the power of 2.

In [37]:
15 ** 2

225

## The double-equality sign

Demonstrate that 100 is not equal to 98.

In [38]:
100 != 98

True

## Reassign Values

Assign the value of 14 to a variable p.

In [39]:
p = 14

Calculate p + 10.

In [40]:
p = p +10

Now, assign 30 to the variable p.

In [199]:
p = 30

Calculate p + 10.

In [200]:
p = p + 10
p

40

Observe how the value of p is always the last one you have assigned.

## Line Continuation

Add a backslash in the code below, so it is a one-line code. Observe the change in the result.

In [45]:
15 + 31 
- 26

-26

In [46]:
15 + 31 \
-26

20

## Indexing Elements

Extract the letter 'B' from "Bingo!".

In [47]:
"Bingo"[0]

'B'

Extract the letter "u" from "Constitution".

In [48]:
"Constitution"[7]

'u'

## Structure Your Code with Indentation

Use indentation properly to print the result of the function with an argument of 3.

In [49]:
def ten(x):
    x = 10
    return x
    
print (ten(3))

10


<hr style="border:5px solid #108999"> </hr>

# Operators <hr style="border:4.5px solid #108999"> </hr>

## Comparison Operators

Verify that 25 is smaller than 30. 

In [50]:
25 < 30

True

Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3. 

In [52]:
(5 * 3) <= (5 **3)

True

Verify that 100 is equal to 10 square.

In [53]:
100 == (10**2)

True

Verify that 53 is not equal to 46.

In [54]:
53 != 46

True

## Logical and Identity Operators

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Check whether the following code is True or False.

False or not True and not False 

In [55]:
False or not True and not False

False

True and not False and True or not False

In [57]:
True and not False and True or not False

True

True or False and False

In [63]:
True or False and False

True

False and True or False

In [65]:
False and True or False

False

Using an identity operator, verify that 10 is not the same as 12.

In [67]:
10 is not 12

<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<ipython-input-67-ddff1d428647>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  10 is not 12


True

Using an identity operator, verify that 50 is the same as 50.

In [68]:
50 is 50

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-68-f043382cab37>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  50 is 50


True

<hr style="border:5px solid #108999"> </hr>

# Conditional Statements <hr style="border:4.5px solid #108999"> </hr>

## Introduction to the IF statement

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.

In [70]:
if 5 >2:
    print("The condition has been satisfied")

The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 or y is less than or equal to 13. 
Change the values assigned to x and y and re-run the cell to verify your code still works.

In [72]:
x,y = (3,25)
if x > 3 and y > 13:
    print("Both conditions are correct")
if x <= 3 or y <= 13:
    print("At least one of the conditions is false")

At least one of the conditions is false


## Add an ELSE Statement

Let x represent the number of orders received during a certain day. 
Assign 102 to x. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise. Change x to 97 to verify your code works properly.

In [74]:
x = 97
if x > 100:
    print("A busy day")
else:
    print("A calm day")

A calm day


## Else if, for Brief - ELIF

Assign 200 to x.
Create the following piece of code:
If x > 200, print out "Big"; 
If x > 100 and x <= 200, print out "Average"; 
and If x <= 100, print out "Small".
Use the If, Elif, and Else keywords in your code.

In [201]:
x = 200

if x > 200:
    print("Big")
elif x >100 and x <= 200:
    print("Average")
else:
    print("Small")

Average


Change the initial value of x to see how your output will vary.

******

Keep the first two conditions of the previous code. Add a new ELIF statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0. 
Let x carry the value of 50 and then of -50 to check if your code is correct.

In [82]:
x =-50

if x > 200:
    print("Big")
elif x >100 and x <= 200:
    print("Average")
elif x>=0 and x <= 100:
    print("Small")
else:
    print("Negative")

Negative


<hr style="border:5px solid #108999"> </hr>

# Functions <hr style="border:4.5px solid #108999"> </hr>

## Creating a Function with a Parameter

Define a function that returns a value equal to its argument multiplied by 2.

In [83]:
def smart(m):
    return m * 2

In [85]:
smart(3)

6

Define a funciton that returns a float value equal to its argument divided by 2.

In [84]:
def NV(m):
    return float(m/2)

In [86]:
NV(2)

1.0

## Another Way to Define a Function

Define a function that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called "result", in the body of the Function. 
Call the function with some argument to verify it works properly.

*Hint: Your knowledge about stating multiple elements on a line can be of great help in solving this exercise!*

In [202]:
def argument(m):
    return f'{m} Raised to the power of 2: {m**2}'

In [203]:
argument(3)

'3 Raised to the power of 2: 9'

## Using a Function in Another Function

Define a function that adds 5 to the parameter. Then, define another function that will multiply the newly obtained number by 3.
Verify your code was correct by calling the second function with an argument of 5. 
Was your output equal to 30?

In [89]:
def add(m):
    return m + 5

def multiply(m):
    return add(m) * 3

multiply(5)
    

30

## Combining Conditional Statements and Functions

Define a function, called **compare_the_two()**, with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [90]:
def compare_the_two(a,b):
    if a > b:
        return "Greater"
    elif a < b: 
        return "Less"
    else:
        return "Equal"

In [204]:
compare_the_two(10,10)

'Equal'

## Notable Built-In Functions in Python

Obtain the maximum number among the values 25, 65, 890, and 15.

In [94]:
max(25,65,890,15)

890

Obtain the minimum number among the values 25, 65, 890, and 15.

In [95]:
min(25,65,890,15)

15

Find the absolute value of -100

In [96]:
abs(-100)

100

Round the value of 55.5. Did you obtain 56.0?

In [205]:
round(55.5)

56

Round 35.56789 to the third digit.

In [100]:
round(35.56789,3)

35.568

Find the sum of all elements in the provided list, called "Numbers".

In [101]:
Numbers = [1, 5, 64, 24.5]

In [102]:
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [103]:
pow(10,3)

1000

How many characters are there in the word "Elephant"?

In [104]:
len("Elephant")

8

Create a function, called "distance_from_zero", that returns the absolute value of a provided single argument and prints a statement "Not Possible" if the argument provided is not a number.
Call the funtion with the values of -10 and "cat" to verify it works correctly.

In [107]:
def distance_from_zero(m):
    if type(m) == str:
        return "Not Possible"
    else:
        return abs(m)
        

In [108]:
distance_from_zero(-10)

10

In [109]:
distance_from_zero("cat")

'Not Possible'

<hr style="border:5px solid #108999"> </hr>

# Sequences <hr style="border:4.5px solid #108999"> </hr>

## Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [110]:
Numbers = [10,25,40,50]

Print the element at index 2 from the list.

In [111]:
print(Numbers[2])

40


Print the 0th element.

In [112]:
print(Numbers[0])

10


Print the third-to-last element using a minus sign in the brackets.

In [113]:
print(Numbers[-3])

25


Substitute the number 10 with the number 15.

In [115]:
Numbers[0] = 15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [118]:
del Numbers[1]
Numbers

[15, 40, 50]

## Help Yourself with Methods

Append the number 100 to the Numbers list. 

In [119]:
Numbers = [15, 40, 50]

In [120]:
Numbers.append(100)

With the help of the "extend method", add the numbers 115 an 140 to the list. 

In [121]:
Numbers.extend([115, 140])
Numbers

[15, 40, 50, 100, 115, 140]

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [122]:
print("The fourth element of the Numbers list is:", Numbers[3])

The fourth element of the Numbers list is: 100


How many elements are there in the Numbers list?

In [123]:
len(Numbers)

6

## List Slicing

In [208]:
Numbers = [15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [125]:
print(Numbers[3:5])

[100, 115]


Using slicing, extract the first four elements from the list.

In [127]:
print(Numbers[:4])

[15, 40, 50, 100]


Using slicing, extract all the elements from the list from the 3rd position onwards.

In [128]:
print(Numbers[3:])

[100, 115, 140]


Using slicing, extract the last 4 elements from the list.

In [209]:
print(Numbers[-4:])

[50, 100, 115, 140]


Which is the position of the value 15?

In [133]:
print(Numbers.index(15))

0


Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists. 

In [210]:
Two_Numbers = [1,2]
All_Numbers = Numbers , Two_Numbers
All_Numbers

([15, 40, 50, 100, 115, 140], [1, 2])

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [136]:
Numbers.sort(reverse= True)
Numbers

[140, 115, 100, 50, 40, 15]

## Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford". 

In [137]:
Cars = ("BMW", "Dodge", "Ford")

Access the second element of this tuple.

In [139]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [211]:
name, age = 'Peter,24'.split(',')

In [212]:
print(name)
print(age)

Peter
24


Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle.
Call the function with arguments 2 and 10 to verify it worked correctly.

In [213]:
def rectangle_info(x,y):
    A = x * y
    P = 2 * (x + y)
    print ("Area and Parameter:")
    return A, P

In [214]:
rectangle_info(2, 10)

Area and Parameter:


(20, 24)

## Dictionaries

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

This is the menu of a close-by restaurant:

In [147]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [148]:
Menu['meal_2']

'Fries'

Add a new meal - "Soup".

In [150]:
Menu['meal_5'] = 'Soup'
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Hamburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Replace the Hamburger with a Cheeseburger.

In [152]:
Menu['meal_3'] = 'Cheeseburger'
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Attach the Desserts list in the form of a sixth meal.

In [154]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [158]:
Menu['Dessert'] =  ['Pancakes', 'Ice-cream', 'Tiramisu']
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 'Dessert': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars):
10, 5, 8, 12, 5. 
Start by *Price_list = {}*.

In [160]:
Price_list =  {
    'meal_1': 10,
    'meal_2': 5,
    'meal_3':8,
    'meal_4':12,
    'meal_5':5
}

Use the *.get()* method to check the price of the Spaghetti.

In [161]:
Price_list.get("meal_1")

10

<hr style="border:5px solid #108999"> </hr>

# Iteration <hr style="border:4.5px solid #108999"> </hr>

## For Loops

Create a For loop that prints every digit on a new line.

In [163]:
digits = [0,1,2,3,4,5,6,7,8,9]

In [164]:
for i in digits:
    print(i)

0
1
2
3
4
5
6
7
8
9


Adjust the code, so the digits are all printed on the same line.

In [165]:
for i in digits:
    print(i, end = ' ')

0 1 2 3 4 5 6 7 8 9 

## While Loops and Incrementing

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Create a while loop that will print all odd numbers from 0 to 30 on the same row. 
<br />
*Hint: There are two ways in which you can create the odd values!*

In [169]:
number = 0

while number < 31:
    if number % 2 != 0:
        print(number, end = ' ')
    number += 1

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 

## Create Lists with the range() Function

Use the range() function to create a list with all numbers from 1 to 10.

In [171]:
print(list(range(1,11)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Use the range() function to create a list with all numbers from 0 to 19.

In [215]:
print(list(range(20)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


Use the range function to create a list with all even numbers from 0 to 30 included.

In [174]:
print(list(range(0,31,2)))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


## Use Conditional Statements and Loops Together

Create a For loop that will print all the variables from a given list multiplied by 2. Let the list contain all numbers from 1 to 10. Create it with the help of the range() function.

In [175]:
for i in range(1,11):
    print(i*2, end= ' ')

2 4 6 8 10 12 14 16 18 20 

Create a little program that runs a loop over all values from 1 to 30. Let it print all Odd numbers, and in the place of the even numbers, it should print "Even".
Help yourself with the range() function to solve this exercise.

In [176]:
for i in range(1,31):
    if i % 2 != 0:
        print(i, end = ' ')
    else:
        print("Even", end = ' ')

1 Even 3 Even 5 Even 7 Even 9 Even 11 Even 13 Even 15 Even 17 Even 19 Even 21 Even 23 Even 25 Even 27 Even 29 Even 

You have the following list of numbers. Iterate over this list, printing out each list value multiplied by 10.
Find two solutions of this problem.

In [223]:
n = [1,2,3,4,5,6]

In [224]:
for i in n:
    print(i*10, end = ' ')

10 20 30 40 50 60 

In [225]:
for i in range(len(n)):
    print(n[i] * 10, end = ' ')

10 20 30 40 50 60 

## All in - Conditional Statements, Functions, and Loops

You are provided with the 'nums' list. Complete the code in the cell that follows. Use a while loop to count the number of values lower than 20. 
*Hint: This exercise is similar to what we did in the video lecture. You might prefer using the x[item] structure for indicating the value of an element from the list.*

In [226]:
nums = [1,12,24,31,51,70,100]

In [227]:
total = 0

for i in nums:
    if i < 20:
        total += 1
print(total)

2


In [234]:
def count(numbers):
    total = 0
    
    while numbers[total] < 20:
        print(numbers[total])
        total += 1
    return total

In [235]:
count(nums)

1
12


2

## Iterating over Dictionaries

In this exercise you will use the same dictionaries as the ones we used in the lesson - "prices" and "quantity". This time, don't just calculate all the money Jan spent. Calculate how much she spent on products with a price of 5 dollars or more.

In [187]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

In [192]:
total_cost = 0

for i in prices:
    if prices[i] >= 5:
        total_cost += (prices[i] * quantity[i])
print(total_cost)        

50


And how much did Jan spent on products that cost less than 5 dollars?

In [193]:
prices = {
    "box_of_spaghetti" : 4,
    "lasagna"  : 5,
    "hamburger" : 2
   }
quantity = {
    "box_of_spaghetti" : 6,
    "lasagna"  : 10,
    "hamburger" : 0
    }

money_spent = 0

for i in prices:
    if prices[i] < 5:
        money_spent += (prices[i] * quantity[i])
print(money_spent)

24
